# Generated by Django 2.2.4 on 2019-10-09 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('route_name', models.CharField(max_length=100)),
                ('extraction_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('thumbnail_url', models.CharField(max_length=400)),
                ('price', models.CharField(max_length=100)),
                ('stock', models.BooleanField()),
                ('product_description', models.CharField(max_length=500)),
                ('upc', models.CharField(max_length=100)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.Category')),
            ],
        ),
    ]
